name: Shane Farthing
favicon: null
layout_spectrum: 0.7692463421262801
typography_spectrum: 0.33319297595880926
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#20151d'
    - '#995c47'
    - '#dc8b6d'
    - '#93a9d4'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
